---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo

- name: "Installing Packages"
  package:
    name:
      - snapd
      - jq
      - pipx
      - ntpdate
      - flameshot
      - exiftool
      - keepassxc
    state: latest
  become: true
  become_method: sudo

# HashiCorp Installation Steps for Ubuntu/Debian
- name: "Install Terraform"
  shell: |
    snap install core && snap install terraform --classic
  become: true
  become_method: sudo

- name: "Install required packages for genymotion"
  apt:
    name:
      - adb
      - virtualbox
    state: latest
  become: true
  become_method: sudo

- name: "Install GoLogin"
  shell: |
    wget https://dl.gologin.com/gologin.tar && tar -xf gologin.tar -C ~/Desktop
  become: true
  become_method: sudo

- name: "Install Postman"
  shell: |
    wget https://dl.pstmn.io/download/latest/linux_64 && tar -xzvf postman-linux-x64.tar.gz -C ~/Desktop
  become: true
  become_method: sudo
