---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo

- name: "Installing Packages"
  package:
    name:
      - xrdp
      - snapd
      - jq
      - pipx
      - ntpdate
      - flameshot
      - exiftool
      - keepassxc
      - proxychains
    state: latest
  become: true
  become_method: sudo

- name: "Start xrdp service"
  systemd:
    name: xrdp
    state: started
  become: true
  become_method: sudo

- name: "Set .xsession content"
  copy:
    content: "mate-session\n"
    dest: "/home/parrot-black/.xsession"
  become: false

- name: "Install Terraform"
  shell: |
    snap install core && snap install terraform --classic
  become: true
  become_method: sudo

- name: "Install packages for genymotion"
  apt:
    name:
      - adb
      - virtualbox
    state: latest
  become: true
  become_method: sudo

- name: "Install genymotion binary"
  get_url:
    url: "https://dl.genymotion.com/releases/genymotion-3.5.0/genymotion-3.5.0-linux_x64.bin"
    dest: "/home/parrot-black/Desktop"
  become: true
  become_method: sudo

- name: "Make binary executable"
  command:
    cmd: "chmod +x /home/parrot-black/Desktop/genymotion-3.5.0-linux_x64.bin"
  become: true
  become_method: sudo

- name: "Install GoLogin"
  get_url:
    url: "https://dl.gologin.com/gologin.tar"
    dest: "/tmp/gologin.tar"
  become: true

- name: "Extract GoLogin"
  unarchive:
    src: "/tmp/gologin.tar"
    dest: "/home/parrot-black/Desktop"
    remote_src: yes
  become: true

- name: "Download Postman"
  get_url:
    url: "https://dl.pstmn.io/download/latest/linux_64"
    dest: "/tmp/linux_64.tar.gz"
  become: true

- name: "Extract Postman"
  unarchive:
    src: "/tmp/linux_64.tar.gz"
    dest: "/home/parrot-black/Desktop"
    remote_src: yes
  become: true

- name: "Download Slack"
  get_url: 
    url: "https://downloads.slack-edge.com/releases/linux/4.34.121/prod/x64/slack-desktop-4.34.121-amd64.deb"
    dest: "/tmp/slack-desktop-4.34.121-amd64.deb"

- name: "Install Slack"
  apt:
    deb: "/tmp/slack-desktop-4.34.121-amd64.deb"

- name: Add list of onion addresses
  content: |
    http://o54hon2e2vj6c7m3aqqu6uyece65by3vgoxxhlqlsvkmacw6a7m7kiad.onion/mulvad
  dest: /home/parrot-black/Desktop/onions.txt

- name: Download mulvad
  get_url:
    url: https://mullvad.net/en/download/app/deb/latest
    dest: /home/parrot-black/Downloads/.