---
- name: "Installing useful github repos"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  loop:
    - { repo: "https://github.com/Flangvik/SharpCollection", dest: "/opt/SharpCollection" }
    - { repo: "https://github.com/danielmiessler/SecLists", dest: "/opt/SecLists" }
  become: true
  become_method: sudo

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
  register: build_dir

- name: "Copying python script to download github releases"
  copy:
    src: "files/githubdownload.py"
    dest: "{{ build_dir.path }}/githubdownload.py"
    owner: root
    group: root
    mode: 0755
  become: true
  become_method: sudo

- name: "Downloading github releases"
  shell: "{{ build_dir.path }}/githubdownload.py {{ item.repo }} {{ item.regex }} {{ item.dest }} {% if item.filename is defined %}{{ item.filename }}{% endif %}"
  loop:
    - { repo: "jpillora/chisel",  regex: "_linux_amd64.gz", dest: "/opt/chisel" }
    - { repo: "jpillora/chisel",  regex: "_windows_amd64.gz", dest: "/opt/chisel" }
    #- { repo: "jpillora/chisel",  regex: "_darwin_amd64", dest: "/opt/chisel", filename: "chisel_osx" }
    - { repo: "carlospolop/PEASS-ng",  regex: "linpeas.sh", dest: "/opt/peas" }
    - { repo: "carlospolop/PEASS-ng",  regex: "winPEASx64.exe", dest: "/opt/peas" }
    - { repo: "WithSecureLabs/chainsaw",  regex: "chainsaw_all_", dest: "/opt/" }
    - { repo: "BloodHoundAD/BloodHound", regex: "BloodHound-linux-x64.zip", dest: "/opt/" }
  async: 45
  poll: 0
  become: true
  become_method: sudo

- name: Remove temporary build directory
  ansible.builtin.file:
    path: "{{ build_dir.path }}"
    state: absent
  when: build_dir.path is defined

- name: Clone private repository
  loop:
    - { repo: "git@github.com:BerenBoden/interesting-infrastructure.git", dest: "/home/kali/Desktop/interesting-infrastructure" }
    - { repo: "git@github.com:BerenBoden/burp-suite.git", dest: "/home/kali/Desktop/interesting-infrastructure/burp-suite" }
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: master
    key_file: /home/kali/.ssh/github
